[package]
name = "funding-service-design-assessment"
version = "0.1.1"
description = "The funding service design frontend for the DLUHC."
authors = ["Version One"]
license = "MIT License"

[tool.black]
line-length = 120
experimental-string-processing = 1

[tool.flake8]
per-file-ignores = [
    './app/assess/routes.py:F405,F403,E731',
]
max-line-length = 120
count = true
