[package]
name = "funding-service-design-assessment"
version = "0.1.1"
description = "The funding service design frontend for the DLUHC."
authors = ["Version One"]
license = "MIT License"

[tool.isort]
profile = "black"
force_single_line = "true"

[tool.flake8]
max-line-length = 120
count = true
