asset_types = {
    "all": "All",
    "community-centre": "Community centre",
    "cinema": "Cinema",
    "gallery": "Gallery",
    "museum": "Museum",
    "music-venue": "Music venue",
    "park": "Park",
    "post-office": "Post office building",
    "pub": "Pub",
    "shop": "Shop",
    "sporting": "Sporting or leisure facility",
    "theatre": "Theatre",
    "other": "Other",
}
